[package]
name = "mips-desktop"
version.workspace = true
edition.workspace = true

[dependencies]
mips-core.path = "../mips-core"
anyhow.workspace = true
bytemuck.workspace = true
eframe = "0.33.3"
egui = "0.33.3"
thiserror = "2.0.11"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[features]

